build: false
environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_UPLOAD: "https://api.bintray.com/conan/uilianries/conan"
    CONAN_REFERENCE: "yaml-cpp/0.2.5"
    CONAN_USERNAME: "uilianries"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
    CONAN_BUILD_TYPES: "Release"
     CONAN_ARCHS: "x86_64"

    matrix:
        - CONAN_CURRENT_PAGE: 1

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade conan conan_package_tools
  - conan user
test_script:
  - python build.py
